import BannerProducts from '@/components/BannerProducts'
import BottomProducts from '@/components/BottomProducts'
import Carrosel from '@/components/Carrosel'
import Categories from '@/components/Categories'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { AppProvider } from '@/context/AppProvider'
import { getCategories } from '@/services/api'
import Head from 'next/head'
import { useEffect, useState } from 'react'


export default function Home() {

  return (
    <AppProvider>
      <Head>
        <title>WS Works Sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className='mainPage'>
        <Categories />
        <div className='centerContainer'>
          <section className='productsContainer'>
            <BannerProducts />
            <Carrosel />
            <BottomProducts />
          </section>
          <Footer />
        </div>
      </section>
      </AppProvider>
  )
}
